version: '3.8'

services:
  react-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DEV=false
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
    volumes:
      - .:/app
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 